# Import libraries: pandas, time and random

In [2]:
import pandas
import time
import random
import requests

# We need to find the file adress from our computer (put \\ for windows). Header and usecols allow to show only the row and column we want

In [3]:
filename= 'C:\\Users\\Noemie\\Desktop\\Cours\\BRANCHE\\(IE)square\\Cours\\US02- Data Science Litteracy\\Data.xlsx'
df = pandas.read_excel(filename, header=2, usecols='B:AR')

# Iteritems is going to list and numerize every country, we just want the country and not the number so we just print v. We split the words with the '('. Strip is to remove the spaces.

In [4]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    print(v.split('(')[0].strip())

Afghanistan
Albania
Armenia
Azerbaijan
Bahrain
Bangladesh
Belarus
Bhutan
Bosnia and Herzegovina
Brunei
Bulgaria
Cambodia
China
Croatia
Czech Republic
East Timor
Egypt
Estonia
France
Georgia
Germany
Hungary
India
Indonesia
Iran
Iraq
Israel
Jordan
Kazakhstan
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lithuania
Macedonia
Malaysia
Maldives
Moldova
Mongolia
Montenegro
Myanmar
Nepal
Oman
Pakistan
Philippines
Poland
Qatar
Romania
Russia
Saudi Arabia
Serbia
Singapore
Slovakia
Slovenia
Sri Lanka
Syria
Tajikistan
Thailiand
The United Arab Emirates
Turkey
Turkmenistan
United Kingdom
United States of America
Ukraine
Uzbekistan
Vietnam
Yemen

# From a website we can obtain some datas.

In [6]:
url = 'http://api.worldbank.org/v2/country/bra/indicator/GC.TAX.IMPT.ZS?format=json'
r = requests.get(url)
print(r.status_code)
data= r.json()
print('data for',data[1][1]['country']['value'],'is',data[1][1]['value'])

200
data for Brazil is 3.87730742935074

# We want the iso name for every country. We can use the function request. Request an API on worldbank.

In [9]:
country_name = 'France'
url = 'https://restcountries.eu/rest/v2/name/' + country_name
r = requests.get(url)
data = r.json ()
print(country_name, data[0]['alpha3Code'])

France FRA

In [10]:
def get_iso_code(country_name):
    try:
        url = 'https://restcountries.eu/rest/v2/name/' + country_name
        r = requests.get(url)
        data = r.json ()
        return data[0]['alpha3Code']
    except KeyError:
        print('[ERROR] cannot get code for', country_name)
        return None
    # print(country, data[0]['alpha3Code'])
    
get_iso_code('Thailand')

'THA'

In [11]:
countries = {}

In [12]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    if country_name not in countries.keys():
        iso_code = get_iso_code(country_name)
        if iso_code is not None:
            countries[country_name]= iso_code
            print (country_name, iso_code)
            time.sleep(0.5+random.random())

Afghanistan AFG
Albania ALB
Armenia ARM
Azerbaijan AZE
Bahrain BHR
Bangladesh BGD
Belarus BLR
Bhutan BTN
Bosnia and Herzegovina BIH
Brunei BRN
Bulgaria BGR
Cambodia KHM
China CHN
Croatia HRV
Czech Republic CZE
East Timor TLS
Egypt EGY
Estonia EST
France FRA
Georgia GEO
Germany DEU
Hungary HUN
India IOT
Indonesia IDN
Iran IRN
Iraq IRQ
Israel ISR
Jordan JOR
Kazakhstan KAZ
Kuwait KWT
Kyrgyzstan KGZ
Laos LAO
Latvia LVA
Lebanon LBN
Lithuania LTU
Macedonia MKD
Malaysia MYS
Maldives MDV
Moldova MDA
Mongolia MNG
Montenegro MNE
Myanmar MMR
Nepal NPL
Oman OMN
Pakistan PAK
Philippines PHL
Poland POL
Qatar QAT
Romania ROU
Russia RUS
Saudi Arabia SAU
Serbia SRB
Singapore SGP
Slovakia SVK
Slovenia SVN
Sri Lanka LKA
Syria SYR
Tajikistan TJK
[ERROR] cannot get code for Thailiand
[ERROR] cannot get code for The United Arab Emirates
Turkey TUR
Turkmenistan TKM
United Kingdom GBR
United States of America USA
Ukraine UKR
Uzbekistan UZB
Vietnam VNM
Yemen YEM

In [13]:
countries['Thailiand']= 'THA'
countries['The United Arab Emirates']= 'ARE'

In [14]:
len(countries.keys()) == len(df['Country (according to CN Gov):'])

True

In [15]:
import pickle
with open('C:\\Users\\Noemie\\Desktop\\Cours\\BRANCHE\\(IE)square\\Cours\\US02- Data Science Litteracy\\countries.pickle','wb+') as fp:
    pickle.dump(countries, fp)

In [16]:
with open('C:\\Users\\Noemie\\Desktop\\Cours\\BRANCHE\\(IE)square\\Cours\\US02- Data Science Litteracy\\countries.pickle','rb') as fp:
    test= pickle.load(fp)
test

{'Afghanistan': 'AFG',
 'Albania': 'ALB',
 'Armenia': 'ARM',
 'Azerbaijan': 'AZE',
 'Bahrain': 'BHR',
 'Bangladesh': 'BGD',
 'Belarus': 'BLR',
 'Bhutan': 'BTN',
 'Bosnia and Herzegovina': 'BIH',
 'Brunei': 'BRN',
 'Bulgaria': 'BGR',
 'Cambodia': 'KHM',
 'China': 'CHN',
 'Croatia': 'HRV',
 'Czech Republic': 'CZE',
 'East Timor': 'TLS',
 'Egypt': 'EGY',
 'Estonia': 'EST',
 'France': 'FRA',
 'Georgia': 'GEO',
 'Germany': 'DEU',
 'Hungary': 'HUN',
 'India': 'IOT',
 'Indonesia': 'IDN',
 'Iran': 'IRN',
 'Iraq': 'IRQ',
 'Israel': 'ISR',
 'Jordan': 'JOR',
 'Kazakhstan': 'KAZ',
 'Kuwait': 'KWT',
 'Kyrgyzstan': 'KGZ',
 'Laos': 'LAO',
 'Latvia': 'LVA',
 'Lebanon': 'LBN',
 'Lithuania': 'LTU',
 'Macedonia': 'MKD',
 'Malaysia': 'MYS',
 'Maldives': 'MDV',
 'Moldova': 'MDA',
 'Mongolia': 'MNG',
 'Montenegro': 'MNE',
 'Myanmar': 'MMR',
 'Nepal': 'NPL',
 'Oman': 'OMN',
 'Pakistan': 'PAK',
 'Philippines': 'PHL',
 'Poland': 'POL',
 'Qatar': 'QAT',
 'Romania': 'ROU',
 'Russia': 'RUS',
 'Saudi Arabia': 'SAU',
 'Serbia': 'SRB',
 'Singapore': 'SGP',
 'Slovakia': 'SVK',
 'Slovenia': 'SVN',
 'Sri Lanka': 'LKA',
 'Syria': 'SYR',
 'Tajikistan': 'TJK',
 'Turkey': 'TUR',
 'Turkmenistan': 'TKM',
 'United Kingdom': 'GBR',
 'United States of America': 'USA',
 'Ukraine': 'UKR',
 'Uzbekistan': 'UZB',
 'Vietnam': 'VNM',
 'Yemen': 'YEM',
 'Thailiand': 'THA',
 'The United Arab Emirates': 'ARE'}

In [17]:
def get_indicator(country_code, indicator):
    head = 'http://api.worldbank.org/v2/country/'
    middle= '/indicator/'
    tail= '?format=json'
    url= head+country_code+middle+indicator+tail
    r = requests.get(url)
    try:
        data= r.json()
        for i in data[1]:
                if i['value'] is None:
                    continue
                else:
                    return i['value']
    except KeyError:
        return None
    except IndexError:
        return None

get_indicator('CHN','GC.TAX.IMPT.ZS')

3.89434134127694

In [18]:
indicator_list={
'IMF WB\nCustoms and other import duties (% of tax revenue) 2016':'GC.TAX.IMPT.ZS',
'WB IMF Non-performing loans to total gross loans ratio (%)':'FB.AST.NPER.ZS',
'UIC Rail freight (mn ton x km travelled)':'IS.RRS.GOOD.MT.K6',
'WB Household final consumption expenditure, PPP bn USD':'NE.CON.PRVT.PP.CD',
'WB UNESCO R&D Expenditure % of GDP':'GB.XPD.RSDV.GD.ZS',
'WB UNESCO Researchers p. mn inhabitants':'SP.POP.SCIE.RD.P6',
'IFDI Net Inflows (% of GDP)':'BX.KLT.DINV.WD.GD.ZS',
'WHO Current Health Expenditure p.c., PPP USD':'SH.XPD.CHEX.PP.CD',
'WB Research Expenditure % of GDP':'GB.XPD.RSDV.GD.ZS',
'WIPO Trademark applications':'IP.TMK.RSCT',
'WIPO Patent Applications':'IP.PAT.RESD'
}

In [19]:
list_columns = ['Country (according to CN Gov):']
for w in indicator_list:
    list_columns.append(w)
    
print(list_columns)

['Country (according to CN Gov):', 'IMF WB\nCustoms and other import duties (% of tax revenue) 2016', 'WB IMF Non-performing loans to total gross loans ratio (%)', 'UIC Rail freight (mn ton x km travelled)', 'WB Household final consumption expenditure, PPP bn USD', 'WB UNESCO R&D Expenditure % of GDP', 'WB UNESCO Researchers p. mn inhabitants', 'IFDI Net Inflows (% of GDP)', 'WHO Current Health Expenditure p.c., PPP USD', 'WB Research Expenditure % of GDP', 'WIPO Trademark applications', 'WIPO Patent Applications']

In [20]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'GC.TAX.IMPT.ZS')
    if value is not None:
        df.at[i,'IMF WB\nCustoms and other import duties (% of tax revenue) 2016']= value
    print(country_name,'done ...')
    time.sleep(0.5+random.random())
df[['Country (according to CN Gov):','IMF WB\nCustoms and other import duties (% of tax revenue) 2016']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

,Country (according to CN Gov):,IMF WB Customs and other import duties (% of tax revenue) 2016
0,Afghanistan,32.551072
1,Albania,2.216459
2,Armenia,6.275395
3,Azerbaijan,4.550383
4,Bahrain,87.914439
5,Bangladesh,28.923008
6,Belarus,8.200619
7,Bhutan,3.052294
8,Bosnia and Herzegovina,0.066132
9,Brunei,NaN
10,Bulgaria,0.072798
11,Cambodia,15.785253
12,China,3.894341
13,Croatia,0.670090
14,Czech Republic,0.819567
15,East Timor,5.741272
16,Egypt,6.849002
17,Estonia,0.039429
18,France (Not BRI),-0.021908
19,Georgia,0.796325
20,Germany (not BRI),0.021249
21,Hungary,-0.000145
22,India,NaN
23,Indonesia,2.463390
24,Iran,20.696450
25,Iraq,14.105211
26,Israel,1.153110
27,Jordan,8.533450
28,Kazakhstan,5.299908
29,Kuwait,66.806723
...,...,...
38,Moldova,3.423233
39,Mongolia,12.087573
40,Montenegro,NaN
41,Myanmar,9.003222
42,Nepal,17.770038
43,Oman,28.368146
44,Pakistan,18.780936
45,Philippines,20.357608
46,Poland,0.128546
47,Qatar,6.021326
48,Romania,0.003434
49,Russia,6.217626
50,Saudi Arabia,NaN
51,Serbia,5.062219
52,Singapore,0.071508
53,Slovakia,0.000290
54,Slovenia,0.808280
55,Sri Lanka,22.054891
56,Syria,10.230756
57,Tajikistan,NaN
58,Thailiand,3.952757
59,The United Arab Emirates,0.381747
60,Turkey,2.418238
61,Turkmenistan,NaN
62,United Kingdom (Not BRI),0.047747
63,United States of America (Not BRI),1.656294
64,Ukraine,3.997681
65,Uzbekistan,5.186860
66,Vietnam,18.427549
67,Yemen,NaN

import tqdm

In [21]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'FB.AST.NPER.ZS')
    if value is not None:
        df.at[i,'WB IMF Non-performing loans to total gross loans ratio (%)']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WB IMF Non-performing loans to total gross loans ratio (%)']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

,Country (according to CN Gov):,WB IMF Non-performing loans to total gross loans ratio (%)
0,Afghanistan,12.201830
1,Albania,13.232533
2,Armenia,5.432318
3,Azerbaijan,NaN
4,Bahrain,NaN
5,Bangladesh,8.397908
6,Belarus,12.852194
7,Bhutan,8.417308
8,Bosnia and Herzegovina,10.046275
9,Brunei,3.538399
10,Bulgaria,10.434453
11,Cambodia,2.072477
12,China,1.744355
13,Croatia,11.201542
14,Czech Republic,3.741720
15,East Timor,NaN
16,Egypt,NaN
17,Estonia,0.698391
18,France (Not BRI),3.080415
19,Georgia,2.778800
20,Germany (not BRI),1.500000
21,Hungary,4.165920
22,India,NaN
23,Indonesia,2.557005
24,Iran,NaN
25,Iraq,NaN
26,Israel,1.290660
27,Jordan,NaN
28,Kazakhstan,9.309768
29,Kuwait,1.949390
...,...,...
38,Moldova,18.377209
39,Mongolia,NaN
40,Montenegro,NaN
41,Myanmar,NaN
42,Nepal,1.699086
43,Oman,NaN
44,Pakistan,8.429489
45,Philippines,1.579311
46,Poland,3.941019
47,Qatar,NaN
48,Romania,6.411894
49,Russia,10.001412
50,Saudi Arabia,1.613649
51,Serbia,NaN
52,Singapore,1.400201
53,Slovakia,3.701005
54,Slovenia,3.203634
55,Sri Lanka,2.498433
56,Syria,NaN
57,Tajikistan,20.389390
58,Thailiand,3.070802
59,The United Arab Emirates,6.435573
60,Turkey,2.842714
61,Turkmenistan,NaN
62,United Kingdom (Not BRI),0.734660
63,United States of America (Not BRI),1.126824
64,Ukraine,54.541296
65,Uzbekistan,0.436415
66,Vietnam,1.824981
67,Yemen,NaN

In [22]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'IS.RRS.GOOD.MT.K6')
    if value is not None:
        df.at[i,'UIC Rail freight (mn ton x km travelled)']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','UIC Rail freight (mn ton x km travelled)']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

,Country (according to CN Gov):,UIC Rail freight (mn ton x km travelled)
0,Afghanistan,NaN
1,Albania,46.000
2,Armenia,640.400
3,Azerbaijan,6210.500
4,Bahrain,NaN
5,Bangladesh,710.000
6,Belarus,41107.000
7,Bhutan,NaN
8,Bosnia and Herzegovina,1139.220
9,Brunei,NaN
10,Bulgaria,2364.370
11,Cambodia,92.000
12,China,1920285.000
13,Croatia,1871.000
14,Czech Republic,10949.000
15,East Timor,NaN
16,Egypt,1592.000
17,Estonia,4807.000
18,France (Not BRI),33116.000
19,Georgia,4261.250
20,Germany (not BRI),72913.000
21,Hungary,446.840
22,India,NaN
23,Indonesia,7166.000
24,Iran,27243.000
25,Iraq,249.000
26,Israel,1155.000
27,Jordan,344.000
28,Kazakhstan,188159.000
29,Kuwait,NaN
...,...,...
38,Moldova,793.000
39,Mongolia,12371.000
40,Montenegro,NaN
41,Myanmar,885.000
42,Nepal,NaN
43,Oman,NaN
44,Pakistan,3301.000
45,Philippines,0.764
46,Poland,28720.000
47,Qatar,NaN
48,Romania,8587.000
49,Russia,2342589.500
50,Saudi Arabia,1852.000
51,Serbia,3086.600
52,Singapore,NaN
53,Slovakia,7072.000
54,Slovenia,3962.630
55,Sri Lanka,135.000
56,Syria,2206.000
57,Tajikistan,228.300
58,Thailiand,2455.000
59,The United Arab Emirates,NaN
60,Turkey,10773.000
61,Turkmenistan,13327.000
62,United Kingdom (Not BRI),19230.000
63,United States of America (Not BRI),2547253.000
64,Ukraine,187557.000
65,Uzbekistan,22937.000
66,Vietnam,3190.000
67,Yemen,NaN

In [23]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'NE.CON.PRVT.PP.CD')
    if value is not None:
        df.at[i,'WB Household final consumption expenditure, PPP bn USD']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WB Household final consumption expenditure, PPP bn USD']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

,Country (according to CN Gov):,"WB Household final consumption expenditure, PPP bn USD"
0,Afghanistan,5.271768e+10
1,Albania,2.400144e+10
2,Armenia,1.989999e+10
3,Azerbaijan,9.360764e+10
4,Bahrain,2.366161e+10
5,Bangladesh,3.756562e+11
6,Belarus,8.166474e+10
7,Bhutan,3.387944e+09
8,Bosnia and Herzegovina,3.124688e+10
9,Brunei,4.203733e+09
10,Bulgaria,8.165409e+10
11,Cambodia,3.763234e+10
12,China,7.627958e+12
13,Croatia,5.385186e+10
14,Czech Republic,1.654772e+11
15,East Timor,1.539284e+09
16,Egypt,8.215885e+11
17,Estonia,1.890269e+10
18,France (Not BRI),1.432813e+12
19,Georgia,2.582765e+10
20,Germany (not BRI),2.076741e+12
21,Hungary,1.243152e+11
22,India,NaN
23,Indonesia,1.438025e+12
24,Iran,5.464230e+11
25,Iraq,2.173399e+11
26,Israel,1.521640e+11
27,Jordan,6.528875e+10
28,Kazakhstan,2.250490e+11
29,Kuwait,7.714014e+10
...,...,...
38,Moldova,1.733193e+10
39,Mongolia,1.554501e+10
40,Montenegro,7.452142e+09
41,Myanmar,1.195639e+11
42,Nepal,5.190158e+10
43,Oman,4.963863e+10
44,Pakistan,7.251701e+11
45,Philippines,5.406112e+11
46,Poland,6.131208e+11
47,Qatar,5.029180e+10
48,Romania,2.887889e+11
49,Russia,1.890556e+12
50,Saudi Arabia,5.502671e+11
51,Serbia,6.585788e+10
52,Singapore,1.311935e+11
53,Slovakia,8.461641e+10
54,Slovenia,3.369016e+10
55,Sri Lanka,1.501184e+11
56,Syria,6.255562e+10
57,Tajikistan,2.119162e+10
58,Thailiand,5.663421e+11
59,The United Arab Emirates,1.690885e+11
60,Turkey,1.057225e+12
61,Turkmenistan,4.250493e+09
62,United Kingdom (Not BRI),1.649155e+12
63,United States of America (Not BRI),1.282069e+13
64,Ukraine,2.687702e+11
65,Uzbekistan,6.919595e+10
66,Vietnam,3.405501e+11
67,Yemen,NaN

In [24]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'GB.XPD.RSDV.GD.ZS')
    if value is not None:
        df.at[i,'WB UNESCO R&D Expenditure % of GDP']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WB UNESCO R&D Expenditure % of GDP']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

        Country (according to CN Gov):  WB UNESCO R&D Expenditure % of GDP
0                          Afghanistan                                 NaN
1                              Albania                             0.15412
2                              Armenia                                 NaN
3                           Azerbaijan                                 NaN
4                              Bahrain                             0.10116
5                           Bangladesh                                 NaN
6                              Belarus                                 NaN
7                               Bhutan                                 NaN
8               Bosnia and Herzegovina                             0.21598
9                               Brunei                             0.03701
10                            Bulgaria                             0.78006
11                            Cambodia                             0.11823
12                               China                             2.10673
13                             Croatia                             0.85621
14                      Czech Republic                             1.67830
15                          East Timor                                 NaN
16                               Egypt                             0.70876
17                             Estonia                             1.28129
18                    France (Not BRI)                             2.24776
19                             Georgia                             0.30104
20                   Germany (not BRI)                             2.93949
21                             Hungary                             1.20606
22                               India                                 NaN
23                           Indonesia                             0.08470
24                                Iran                             0.25267
25                                Iraq                             0.03631
26                              Israel                             4.25121
27                              Jordan                             0.33201
28                          Kazakhstan                             0.14179
29                              Kuwait                             0.42705
..                                 ...                                 ...
38                             Moldova                             0.33114
39                            Mongolia                                 NaN
40                          Montenegro                             0.37400
41                             Myanmar                             0.16216
42                               Nepal                             0.30220
43                                Oman                             0.24647
44                            Pakistan                             0.24605
45                         Philippines                             0.13793
46                              Poland                             0.96538
47                               Qatar                             0.50969
48                             Romania                             0.48264
49                              Russia                             1.09690
50                        Saudi Arabia                                 NaN
51                              Serbia                             0.89059
52                           Singapore                             2.18377
53                            Slovakia                             0.78965
54                            Slovenia                             2.00202
55                           Sri Lanka                             0.09989
56                               Syria                                 NaN
57                          Tajikistan                                 NaN
58                           Thailiand                             0.61927
59            The United Arab Emirates                             0.98660
60                              Turkey                             0.88150
61                        Turkmenistan                                 NaN
62            United Kingdom (Not BRI)                             1.69036
63  United States of America (Not BRI)                             2.74418
64                             Ukraine                             0.48384
65                          Uzbekistan                             0.22089
66                             Vietnam                             0.44113
67                               Yemen                                 NaN

[68 rows x 2 columns]

In [25]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'NE.CON.PRVT.PP.CD')
    if value is not None:
        df.at[i,'WB Household final consumption expenditure, PPP bn USD']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WB Household final consumption expenditure, PPP bn USD']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

,Country (according to CN Gov):,"WB Household final consumption expenditure, PPP bn USD"
0,Afghanistan,5.271768e+10
1,Albania,2.400144e+10
2,Armenia,1.989999e+10
3,Azerbaijan,9.360764e+10
4,Bahrain,2.366161e+10
5,Bangladesh,3.756562e+11
6,Belarus,8.166474e+10
7,Bhutan,3.387944e+09
8,Bosnia and Herzegovina,3.124688e+10
9,Brunei,4.203733e+09
10,Bulgaria,8.165409e+10
11,Cambodia,3.763234e+10
12,China,7.627958e+12
13,Croatia,5.385186e+10
14,Czech Republic,1.654772e+11
15,East Timor,1.539284e+09
16,Egypt,8.215885e+11
17,Estonia,1.890269e+10
18,France (Not BRI),1.432813e+12
19,Georgia,2.582765e+10
20,Germany (not BRI),2.076741e+12
21,Hungary,1.243152e+11
22,India,NaN
23,Indonesia,1.438025e+12
24,Iran,5.464230e+11
25,Iraq,2.173399e+11
26,Israel,1.521640e+11
27,Jordan,6.528875e+10
28,Kazakhstan,2.250490e+11
29,Kuwait,7.714014e+10
...,...,...
38,Moldova,1.733193e+10
39,Mongolia,1.554501e+10
40,Montenegro,7.452142e+09
41,Myanmar,1.195639e+11
42,Nepal,5.190158e+10
43,Oman,4.963863e+10
44,Pakistan,7.251701e+11
45,Philippines,5.406112e+11
46,Poland,6.131208e+11
47,Qatar,5.029180e+10
48,Romania,2.887889e+11
49,Russia,1.890556e+12
50,Saudi Arabia,5.502671e+11
51,Serbia,6.585788e+10
52,Singapore,1.311935e+11
53,Slovakia,8.461641e+10
54,Slovenia,3.369016e+10
55,Sri Lanka,1.501184e+11
56,Syria,6.255562e+10
57,Tajikistan,2.119162e+10
58,Thailiand,5.663421e+11
59,The United Arab Emirates,1.690885e+11
60,Turkey,1.057225e+12
61,Turkmenistan,4.250493e+09
62,United Kingdom (Not BRI),1.649155e+12
63,United States of America (Not BRI),1.282069e+13
64,Ukraine,2.687702e+11
65,Uzbekistan,6.919595e+10
66,Vietnam,3.405501e+11
67,Yemen,NaN

In [26]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'SP.POP.SCIE.RD.P6')
    if value is not None:
        df.at[i,'WB UNESCO Researchers p. mn inhabitants']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WB UNESCO Researchers p. mn inhabitants']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

,Country (according to CN Gov):,WB UNESCO Researchers p. mn inhabitants
0,Afghanistan,NaN
1,Albania,156.101105
2,Armenia,NaN
3,Azerbaijan,NaN
4,Bahrain,368.902344
5,Bangladesh,NaN
6,Belarus,NaN
7,Bhutan,NaN
8,Bosnia and Herzegovina,404.399902
9,Brunei,283.431091
10,Bulgaria,2243.709473
11,Cambodia,30.374470
12,China,1205.682495
13,Croatia,1793.146118
14,Czech Republic,3518.818848
15,East Timor,NaN
16,Egypt,680.302795
17,Estonia,3305.288818
18,France (Not BRI),4307.222168
19,Georgia,1336.562744
20,Germany (not BRI),4893.152832
21,Hungary,2645.673828
22,India,NaN
23,Indonesia,89.199287
24,Iran,671.023987
25,Iraq,63.732079
26,Israel,8250.474609
27,Jordan,598.574280
28,Kazakhstan,687.635193
29,Kuwait,385.690918
...,...,...
38,Moldova,725.741333
39,Mongolia,NaN
40,Montenegro,832.996399
41,Myanmar,17.755541
42,Nepal,61.059151
43,Oman,215.954773
44,Pakistan,293.646912
45,Philippines,187.658981
46,Poland,2158.460938
47,Qatar,603.790649
48,Romania,912.424133
49,Russia,2979.095215
50,Saudi Arabia,NaN
51,Serbia,2132.772705
52,Singapore,6729.679688
53,Slovakia,2598.904053
54,Slovenia,3899.200195
55,Sri Lanka,99.740280
56,Syria,NaN
57,Tajikistan,NaN
58,Thailiand,865.395813
59,The United Arab Emirates,2406.573242
60,Turkey,1215.778320
61,Turkmenistan,NaN
62,United Kingdom (Not BRI),4429.583984
63,United States of America (Not BRI),4313.383301
64,Ukraine,1037.240845
65,Uzbekistan,505.965698
66,Vietnam,672.073792
67,Yemen,NaN

In [27]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'BX.KLT.DINV.WD.GD.ZS')
    if value is not None:
        df.at[i,'IFDI Net Inflows (% of GDP)']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','IFDI Net Inflows (% of GDP)']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

        Country (according to CN Gov):  IFDI Net Inflows (% of GDP)
0                          Afghanistan                     0.273179
1                              Albania                     7.839316
2                              Armenia                     2.164932
3                           Azerbaijan                     7.037159
4                              Bahrain                     1.469627
5                           Bangladesh                     0.861500
6                              Belarus                     2.343707
7                               Bhutan                    -0.654814
8               Bosnia and Herzegovina                     2.562925
9                               Brunei                     3.858213
10                            Bulgaria                     3.747996
11                            Cambodia                    12.582625
12                               China                     1.374634
13                             Croatia                     3.695610
14                      Czech Republic                     4.269351
15                          East Timor                     0.227303
16                               Egypt                     3.140471
17                             Estonia                     5.999697
18                    France (Not BRI)                     1.832937
19                             Georgia                    12.133758
20                   Germany (not BRI)                     2.120590
21                             Hungary                    -9.690974
22                               India                          NaN
23                           Indonesia                     2.113612
24                                Iran                     1.105476
25                                Iraq                    -2.620212
26                              Israel                     5.178530
27                              Jordan                     5.065645
28                          Kazakhstan                     2.857327
29                              Kuwait                     0.094078
..                                 ...                          ...
38                             Moldova                     1.978718
39                            Mongolia                    13.069774
40                          Montenegro                    11.565272
41                             Myanmar                     6.985207
42                               Nepal                     0.788838
43                                Oman                     4.017028
44                            Pakistan                     0.923097
45                         Philippines                     3.207124
46                              Poland                     2.027292
47                               Qatar                     0.590665
48                             Romania                     2.809515
49                              Russia                     1.810270
50                        Saudi Arabia                     0.206964
51                              Serbia                     6.948354
52                           Singapore                    19.645574
53                            Slovakia                     6.183240
54                            Slovenia                     2.218344
55                           Sri Lanka                     1.573877
56                               Syria                     3.073775
57                          Tajikistan                     1.501005
58                           Thailiand                     1.767068
59            The United Arab Emirates                     2.706455
60                              Turkey                     1.278376
61                        Turkmenistan                     6.099995
62            United Kingdom (Not BRI)                     2.466617
63  United States of America (Not BRI)                     1.829897
64                             Ukraine                     2.520637
65                          Uzbekistan                     0.192777
66                             Vietnam                     6.300835
67                               Yemen                    -0.863032

[68 rows x 2 columns]

In [28]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'SH.XPD.CHEX.PP.CD')
    if value is not None:
        df.at[i,'WHO Current Health Expenditure p.c., PPP USD']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WHO Current Health Expenditure p.c., PPP USD']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

,Country (according to CN Gov):,"WHO Current Health Expenditure p.c., PPP USD"
0,Afghanistan,183.927858
1,Albania,773.678292
2,Armenia,883.220652
3,Azerbaijan,1191.289459
4,Bahrain,2453.155914
5,Bangladesh,88.035356
6,Belarus,1084.619757
7,Bhutan,287.128628
8,Bosnia and Herzegovina,1101.792914
9,Brunei,2083.430502
10,Bulgaria,1491.868089
11,Cambodia,209.616863
12,China,762.243779
13,Croatia,1656.426156
14,Czech Republic,2469.851757
15,East Timor,141.275828
16,Egypt,495.165081
17,Estonia,1886.814387
18,France (Not BRI),4542.307106
19,Georgia,717.716242
20,Germany (not BRI),5356.811177
21,Hungary,1912.069053
22,India,NaN
23,Indonesia,369.286440
24,Iran,1261.730503
25,Iraq,481.039845
26,Israel,2819.111414
27,Jordan,568.122532
28,Kazakhstan,903.324091
29,Kuwait,2977.514144
...,...,...
38,Moldova,515.323073
39,Mongolia,469.563584
40,Montenegro,957.014821
41,Myanmar,267.228033
42,Nepal,150.590369
43,Oman,1635.870769
44,Pakistan,134.441461
45,Philippines,322.778000
46,Poland,1704.195989
47,Qatar,3900.286232
48,Romania,1090.416516
49,Russia,1414.028282
50,Saudi Arabia,3121.341632
51,Serbia,1323.690595
52,Singapore,3681.295940
53,Slovakia,2061.950585
54,Slovenia,2733.762624
55,Sri Lanka,353.129150
56,Syria,159.716094
57,Tajikistan,192.696191
58,Thailiand,610.170004
59,The United Arab Emirates,2425.795649
60,Turkey,995.966037
61,Turkmenistan,1003.781827
62,United Kingdom (Not BRI),4144.600790
63,United States of America (Not BRI),9535.945335
64,Ukraine,469.428377
65,Uzbekistan,382.821710
66,Vietnam,334.319988
67,Yemen,144.499884

In [40]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'GB.XPD.RSDV.GD.ZS')
    if value is not None:
        df.at[i,'WB Research Expenditure % of GDP']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WB Research Expenditure % of GDP']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

        Country (according to CN Gov):  WB Research Expenditure % of GDP
0                          Afghanistan                               NaN
1                              Albania                           0.15412
2                              Armenia                               NaN
3                           Azerbaijan                               NaN
4                              Bahrain                           0.10116
5                           Bangladesh                               NaN
6                              Belarus                               NaN
7                               Bhutan                               NaN
8               Bosnia and Herzegovina                           0.21598
9                               Brunei                           0.03701
10                            Bulgaria                           0.78006
11                            Cambodia                           0.11823
12                               China                           2.10673
13                             Croatia                           0.85621
14                      Czech Republic                           1.67830
15                          East Timor                               NaN
16                               Egypt                           0.70876
17                             Estonia                           1.28129
18                    France (Not BRI)                           2.24776
19                             Georgia                           0.30104
20                   Germany (not BRI)                           2.93949
21                             Hungary                           1.20606
22                               India                               NaN
23                           Indonesia                           0.08470
24                                Iran                           0.25267
25                                Iraq                           0.03631
26                              Israel                           4.25121
27                              Jordan                           0.33201
28                          Kazakhstan                           0.14179
29                              Kuwait                           0.42705
..                                 ...                               ...
38                             Moldova                           0.33114
39                            Mongolia                               NaN
40                          Montenegro                           0.37400
41                             Myanmar                           0.16216
42                               Nepal                           0.30220
43                                Oman                           0.24647
44                            Pakistan                           0.24605
45                         Philippines                           0.13793
46                              Poland                           0.96538
47                               Qatar                           0.50969
48                             Romania                           0.48264
49                              Russia                           1.09690
50                        Saudi Arabia                               NaN
51                              Serbia                           0.89059
52                           Singapore                           2.18377
53                            Slovakia                           0.78965
54                            Slovenia                           2.00202
55                           Sri Lanka                           0.09989
56                               Syria                               NaN
57                          Tajikistan                               NaN
58                           Thailiand                           0.61927
59            The United Arab Emirates                           0.98660
60                              Turkey                           0.88150
61                        Turkmenistan                               NaN
62            United Kingdom (Not BRI)                           1.69036
63  United States of America (Not BRI)                           2.74418
64                             Ukraine                           0.48384
65                          Uzbekistan                           0.22089
66                             Vietnam                           0.44113
67                               Yemen                               NaN

[68 rows x 2 columns]

In [41]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'IP.TMK.RSCT')
    if value is not None:
        df.at[i,'WIPO Trademark applications']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WIPO Trademark applications']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

        Country (according to CN Gov):  WIPO Trademark applications
0                          Afghanistan                          NaN
1                              Albania                        918.0
2                              Armenia                       2356.0
3                           Azerbaijan                       2817.0
4                              Bahrain                        371.0
5                           Bangladesh                       8580.0
6                              Belarus                       4652.0
7                               Bhutan                         16.0
8               Bosnia and Herzegovina                        797.0
9                               Brunei                         85.0
10                            Bulgaria                      14243.0
11                            Cambodia                       1182.0
12                               China                    3526953.0
13                             Croatia                       4334.0
14                      Czech Republic                      19301.0
15                          East Timor                          NaN
16                               Egypt                      12750.0
17                             Estonia                       1999.0
18                    France (Not BRI)                     258090.0
19                             Georgia                       2217.0
20                   Germany (not BRI)                     190216.0
21                             Hungary                       9318.0
22                               India                          NaN
23                           Indonesia                      48756.0
24                                Iran                     177538.0
25                                Iraq                          NaN
26                              Israel                       3463.0
27                              Jordan                       3013.0
28                          Kazakhstan                       8495.0
29                              Kuwait                          NaN
..                                 ...                          ...
38                             Moldova                       3049.0
39                            Mongolia                       7629.0
40                          Montenegro                          3.0
41                             Myanmar                       4422.0
42                               Nepal                       3215.0
43                                Oman                          1.0
44                            Pakistan                      27017.0
45                         Philippines                      22357.0
46                              Poland                      39420.0
47                               Qatar                       1405.0
48                             Romania                      20575.0
49                              Russia                     193213.0
50                        Saudi Arabia                       7423.0
51                              Serbia                       3431.0
52                           Singapore                       9721.0
53                            Slovakia                       9436.0
54                            Slovenia                          8.0
55                           Sri Lanka                       6893.0
56                               Syria                          1.0
57                          Tajikistan                        160.0
58                           Thailiand                      35720.0
59            The United Arab Emirates                       5199.0
60                              Turkey                     193824.0
61                        Turkmenistan                          NaN
62            United Kingdom (Not BRI)                     114722.0
63  United States of America (Not BRI)                     388504.0
64                             Ukraine                      45880.0
65                          Uzbekistan                       6457.0
66                             Vietnam                      54965.0
67                               Yemen                       2561.0

[68 rows x 2 columns]

In [42]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name= v.split('(')[0].strip()
    country_code = countries[country_name]
    value= get_indicator(country_code,'IP.PAT.RESD')
    if value is not None:
        df.at[i,'WIPO Patent Applications']= value
    print(country_name,'done ...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','WIPO Patent Applications']]

Afghanistan done ...
Albania done ...
Armenia done ...
Azerbaijan done ...
Bahrain done ...
Bangladesh done ...
Belarus done ...
Bhutan done ...
Bosnia and Herzegovina done ...
Brunei done ...
Bulgaria done ...
Cambodia done ...
China done ...
Croatia done ...
Czech Republic done ...
East Timor done ...
Egypt done ...
Estonia done ...
France done ...
Georgia done ...
Germany done ...
Hungary done ...
India done ...
Indonesia done ...
Iran done ...
Iraq done ...
Israel done ...
Jordan done ...
Kazakhstan done ...
Kuwait done ...
Kyrgyzstan done ...
Laos done ...
Latvia done ...
Lebanon done ...
Lithuania done ...
Macedonia done ...
Malaysia done ...
Maldives done ...
Moldova done ...
Mongolia done ...
Montenegro done ...
Myanmar done ...
Nepal done ...
Oman done ...
Pakistan done ...
Philippines done ...
Poland done ...
Qatar done ...
Romania done ...
Russia done ...
Saudi Arabia done ...
Serbia done ...
Singapore done ...
Slovakia done ...
Slovenia done ...
Sri Lanka done ...
Syria done ...
Tajikistan done ...
Thailiand done ...
The United Arab Emirates done ...
Turkey done ...
Turkmenistan done ...
United Kingdom done ...
United States of America done ...
Ukraine done ...
Uzbekistan done ...
Vietnam done ...
Yemen done ...

        Country (according to CN Gov):  WIPO Patent Applications
0                          Afghanistan                       NaN
1                              Albania                      21.0
2                              Armenia                     125.0
3                           Azerbaijan                     144.0
4                              Bahrain                       6.0
5                           Bangladesh                      77.0
6                              Belarus                     455.0
7                               Bhutan                       3.0
8               Bosnia and Herzegovina                      60.0
9                               Brunei                      26.0
10                            Bulgaria                     230.0
11                            Cambodia                       2.0
12                               China                 1204981.0
13                             Croatia                     175.0
14                      Czech Republic                     792.0
15                          East Timor                       NaN
16                               Egypt                     918.0
17                             Estonia                      29.0
18                    France (Not BRI)                   14206.0
19                             Georgia                      96.0
20                   Germany (not BRI)                   48480.0
21                             Hungary                     616.0
22                               India                       NaN
23                           Indonesia                    1101.0
24                                Iran                   14930.0
25                                Iraq                     335.0
26                              Israel                    1300.0
27                              Jordan                      22.0
28                          Kazakhstan                     993.0
29                              Kuwait                       4.0
..                                 ...                       ...
38                             Moldova                      91.0
39                            Mongolia                     112.0
40                          Montenegro                      10.0
41                             Myanmar                       NaN
42                               Nepal                      11.0
43                                Oman                       NaN
44                            Pakistan                     204.0
45                         Philippines                     327.0
46                              Poland                    4261.0
47                               Qatar                      16.0
48                             Romania                    1005.0
49                              Russia                   26795.0
50                        Saudi Arabia                    1070.0
51                              Serbia                     192.0
52                           Singapore                    1601.0
53                            Slovakia                     220.0
54                            Slovenia                     470.0
55                           Sri Lanka                     280.0
56                               Syria                     198.0
57                          Tajikistan                       2.0
58                           Thailiand                    1098.0
59            The United Arab Emirates                      15.0
60                              Turkey                    6230.0
61                        Turkmenistan                      44.0
62            United Kingdom (Not BRI)                   13876.0
63  United States of America (Not BRI)                  295327.0
64                             Ukraine                    2233.0
65                          Uzbekistan                     353.0
66                             Vietnam                     560.0
67                               Yemen                      16.0

[68 rows x 2 columns]

In [43]:
df.to_excel(excel_writer = 'C:\\Users\\Noemie\\Desktop\\Cours\\BRANCHE\\(IE)square\\Cours\\US02- Data Science Litteracy\\Data2.xlsx',sheet_name = 'Data', na_rep = 'NaN', float_format = '%.2f', columns = list_columns)